#!/usr/bin/env python

''''
		ics2gCal.py
		
		Copyright 2010 Pål Levold		
		
    This file is part of ics2gCal.

    ics2gCal is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ics2gCal is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
''''

from GCal import GCal
from IcsAdder import IcsAdder
import ConfigParser
import urllib2
import hashlib
import smtplib
from datetime import datetime
import os
	
def main():
	configFileName = 'config'
	settingsSection = 'settings'
	
	config = ConfigParser.ConfigParser()
	config.read(configFileName)
	
	#Getting settings
	username = config.get(settingsSection,'username')
	password = config.get(settingsSection,'password')
	eventFile = config.get(settingsSection,'eventFile')
	

	icsFeeds = list()
	anyChange = False
	for feedId in config.sections():
		if feedId == settingsSection: 
			continue

		url = config.get(feedId,'url')
		sha1 = config.get(feedId,'sha1')

		icsFeed = urllib2.urlopen(url).read()
		
		h = hashlib.sha1()
		h.update(icsFeed)
		print "Old:" + sha1
		print "New:" + h.hexdigest()
		
		if sha1 != h.hexdigest():
			anyChange = True
			icsFeeds.append(icsFeed)
			config.set(feedId, 'sha1', h.hexdigest())
		else:
			icsFeeds.append(None)
	
	if anyChange == False:
		print "No changes"
		return 1
	else:
		print "Changes to be added..."
	
	#Getting added events
	print "Getting added events..."
	addedEventsFile = open(eventFile,"r+")	
	addedEventsList = list()
	line = addedEventsFile.readline()
	while len(line) != 0:
		tmp = list()
		lineSplit = line.split()
		tmp.append(lineSplit[0])
		tmp.append(lineSplit[1])
		addedEventsList.append(tmp)
		
		line = addedEventsFile.readline()
	
	#Create gCal object
	print "Logging into Google..."
	gCal = GCal(username,password)
	
	i = 0
	addedEvents = 0
	for feedId in config.sections():
		if feedId == settingsSection or icsFeeds[i] == None: 
			continue
		
		addTo = config.get(feedId,"addTo")
		
		print "Adding new events..."
		adder = IcsAdder(icsFeeds[i], feedId, gCal, addTo, addedEventsFile, addedEventsList)
		adder.addEvents()
		addedEvents = addedEvents + adder.getNumAddedEvents()
			
	#Update config file
	print "Updating config file..."
	if anyChange == True:
		f = open(configFileName, "w")
		config.write(f)
		f.close()
		
	print str(addedEvents) + " events added to calendar"
	
	if addedEvents > 0:
		print "Sending email notification..."
		server = smtplib.SMTP('smtp.gmail.com:587')
		server.starttls()
		server.login(username,password)
		
		now = datetime.now().strftime("%Y %m.%d %H:%M:%S")
		
		host = os.getenv("HOSTNAME")
		if host == None:
			host = "(Unknown)"
		
		msg = "Subject: [" + now + "] ics2gCal added " + str(addedEvents) + " event(s) to gCal\n\n" \
					+ "[" + now + "] " + str(addedEvents) + " event(s) added to gCal\n\n" \
					+ "----------------------------------------------------------------------------------------------------------\n" \
					+ "This is an automatic email generated by the ics2gCal script running on " + host
		
		server.sendmail(username,username,msg)
		server.quit()
	
	print "Done!"
if __name__ == "__main__":
	main()
